name: Build ANDROID

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name'
        required: true
        type: string
      release_tag:
        description: 'Release tag'
        required: true
        type: string
      release_body:
        description: 'Release body'
        required: true
        type: string

jobs:
  build-android:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: CD into the beeware project
        run: |
          cd tg-ws-proxy-android
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Create virtual environment
        run: |
          python -m venv venv
      
      - name: Test venv activation
        run: |
          python -c "import sys; print('Inside venv') if sys.prefix != sys.base_prefix else print('Not in venv')"
      
      - name: Install dependencies
        run: |
          python -m pip install briefcase cryptography

      - name: Create android build stub
        run: |
          briefcase create android
          briefcase build android
      
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dir
          gh release create release-${{ github.event.inputs.release_tag }} `
            --title "${{ github.event.inputs.release_name }}" `
            --notes "${{ github.event.inputs.release_body }}" `
            ./tg-ws-proxy-android/build/tg-ws-proxy-android/android/gradle/app/build/outputs/apk/debug/app-debug.apk
